- name : Testing connectvty to Host
  hosts: fronend

  tasks:
    - name: ping Testing
      ansible.builtin.ping

    - name: print ping_result
      ansible.builin.debug
        msg: "Hi this is test"