- name : Testing connectvty to Host
  hosts: fronend

  tasks:
    - name: ping Testing
      ansible.builtin.ping
      register: ping_result

    - name: print ping_result
      ansible.builin.debug
        msg: {{ ping_result }}